from packetsniffer import *
import os
from dotenv import load_dotenv
from google import genai
from google.genai import errors
import json

load_dotenv()
credentials = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS")
project_name = os.environ.get("PROJECT_NAME")


def scan_pcap(file_path, trainer, trained_model, bottleneck, dataset, labels):
    # Set up Gemini client and verify connection
    try:
        client = genai.Client(vertexai=True, project=project_name, location='us-central1')

    except errors.ClientError as cerr:
        print(f"\n** Caught Google Cloud Client Authentication error: {cerr}")
        return None, None

    except errors.ServerError as serr:
        print(f"\n** Caught Google Cloud Server error: {serr}")
        return None, None

    except Exception as err:
        print(f"\n** Caught runtime error: {err}")
        return None, None

    # Retrieve network traffic data from pcap file for analysis
    content = retrieve_pcap_content(r'{}'.format(file_path))
    traffic = recordTraffic(content)
    sessions = retrieve_payloads(traffic)                                                                                                                                       
    # Find predictions from retrieved payload data
    predictions = trainer.get_predictions(trained_model, sessions,
                                              bottleneck, dataset)

    # Convert predictions from floats to integers
    predictions = [int(p) for p in predictions]
    mappings = list(zip(predictions, sessions))

    # Read testing data output generated by Gemini
    with open(f"testOutput.txt", "r", encoding="utf-8") as file:
        text = file.read()

        # Clean up unstructured json text to help with decoding
        text = text.replace("```", "")
        split_text = text.split("json")
        filtered_text = [s.strip("\n") for s in split_text if s]
        merged_text = ", ".join(filtered_text)
        formatted_text = f"[{merged_text}]"

        # Parse text into json-readable format
        parsed_text = json.loads(formatted_text)

        try:
            # Make final prediction using previous output and new inputs
            result = client.models.generate_content(model="gemini-2.5-flash",
                                                    contents=
                                                    f"""
                                                    This is the baseline dataset containing network traffic data: {bottleneck}.
                                                    These are the cluster labels: {labels}.
                                                    These are the predictions made for this training data: {parsed_text}.

                                                    Using this data, I want you to make the final predictions for each input in the prompt that I will provide you.

                                                    You may come up with either already discovered or undiscovered cyber threats that are associated with the cluster that each input belongs to.

                                                    Include the source and destination IP addresses, port number, and protocol used in each input.

                                                    Just to provide more context, you are a cybersecurity analyst who is analyzing this data and predicting whether each input represents either a Non-threat or a Threat.

                                                    Respond in the following format:

                                                    {{
                                                        "Cluster ID": <int>,
                                                        "Behavior Description": "...",
                                                        "Threat Assessment": "...",
                                                        "Label": "<Non-threat | Threat Type>",
                                                        // Only include this field if the "Label" is a Threat Type
                                                        "Recommended Solution": {{
                                                            "Steps": [
                                                                "...",
                                                                "..."
                                                            ],
                                                            "Explanation": "...",
                                                            "Success Rate": "..."
                                                        }},

                                                        // Only include this field if the "Label" is a Threat Type
                                                        "Alternative Solution(s)": [
                                                            "1. ...",
                                                            "2. ..."
                                                            ]
                                                    }}

                                                    Please keep this entire response as concise and descriptive as possible.

                                                    Here is my prompt for you to analyze: {mappings}

                                                    This input data pairs each conversation between two IP addresses with an assigned label (cluster id), representing the cluster they are the most closely aligned with.
                                                    """)

            print("Successfully generated response.")
            return result, sessions

        except errors.APIError as aerr:
            print(f"\n** Caught issue from Gemini response: {aerr}")
            return None, None

        except Exception as err:
            print(f"\n** Caught runtime error: {err}")
            return None, None
