from analysis.packetsniffer import *                                                             
import os
from dotenv import load_dotenv
from google import genai
from google.genai import errors
import json

load_dotenv()
credentials = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS")
project_name = os.environ.get("PROJECT_NAME")

def scan_pcap(file_path, trainer, trained_model, bottleneck, dataset, labels):
    # Set up Gemini client and verify connection
    try:
        client = genai.Client(vertexai=True, project=project_name, location='us-central1')
    
    except errors.ClientError as cerr:
        print(f"\n** Caught Google Cloud Client Authentication error: {cerr}")
        return None, None
    
    except errors.ServerError as serr:
        print(f"\n** Caught Google Cloud Server error: {serr}")
        return None, None

    except Exception as err:
        print(f"\n** Caught runtime error: {err}")
        return None, None

    # Retrieve network traffic data from pcap file for analysis
    content = retrieve_pcap_content(r'{}'.format(file_path))
    traffic = recordTraffic(content)
    sessions = retrieve_payloads(traffic)

    # Find predictions from retrieved payload data
    predictions = trainer.get_predictions(trained_model, sessions,
                                              bottleneck, dataset)

    # Convert predictions from floats to integers
    predictions = [int(p) for p in predictions]
    mappings = list(zip(predictions, sessions))

    # Read testing data output generated by Gemini
    with open(f"training/testOutput.txt", "r", encoding="utf-8") as file:
        text = file.read()

        # Clean up unstructured json text to help with decoding
        text = text.replace("```", "")
        split_text = text.split("json")
        filtered_text = [s.strip("\n") for s in split_text if s]
        merged_text = ", ".join(filtered_text)
        formatted_text = f"[{merged_text}]"

        # Parse text into json-readable format
        parsed_text = json.loads(formatted_text)
        
        try:
            # Make final prediction using previous output and new inputs
            result = client.models.generate_content(model="gemini-2.5-flash",
                                                    contents=
                                                    f"""
                                                    This is the baseline dataset containing network traffic data: {bottleneck}.
                                                    These are the cluster labels: {labels}.
                                                    These are the predictions made for this training data: {parsed_text}.

                                                    Using this data, I want you to make a final prediction for each input in the prompt that I will provide you.

                                                    You may identify known or previously undiscovered cyber threats associated with the cluster to which an input belongs.

                                                    As a cybersecurity analyst, determine whether each input represents a Non-threat or a Threat.

                                                    Return a valid JSON array. Each element must be a JSON object in the following format:
                                                    
                                                    [
                                                    {{
                                                        "Cluster ID": <int>,
                                                        "Behavior Description": "...",
                                                        "Threat Assessment": "...",
                                                        "Label": "<Non-threat | Threat Type>",
                                                        // Only include this field if the "Label" is a Threat Type
                                                        "Recommended Solution": {{
                                                            "Steps": [
                                                                "...",
                                                                "..."
                                                            ],
                                                            "Explanation": "...",
                                                            "Success Rate": "..."
                                                        }},

                                                        // Only include this field if the "Label" is a Threat Type
                                                        "Alternative Solution(s)": [
                                                            "1. ...",
                                                            "2. ..."
                                                        ]
                                                    }}
                                                    ]

                                                    Rules:

                                                    - Return JSON only.
                                                    - Return a JSON array, not markdown.
                                                    - Do NOT use Markdown.
                                                    - Do NOT include wrappers.
                                                    - Do NOT include any explanation, commentary, or formatting.
                                                    - The response must start with [ and end with ].
                                                    - The output must be valid raw JSON parsable by json.loads() without modification.
                                                    - Use double quotes for all keys and string values.
                                                    - If Label is "Non-threat", omit "Recommended Solution" and "Alternative Solution(s)".
                                                    - If Label is a threat type, include both conditional fields.
                                                    - If Label is a threat type, do not prefix it with "Threat -".
                                                    - Omit conditional fields when Label = "Non-threat".
                                                    - Do not number items in "Steps".
                                                    - Keep all values concise and descriptive.
                                                    - Minimize token usage.

                                                    Here is my prompt for you to analyze: {mappings}

                                                    This input data pairs each conversation between two IP addresses with an assigned label (cluster id), representing the cluster they are the most closely aligned with.
                                                    """)

            # Write results to text file
            output = result.text
            with open("analysis/result.txt", "w") as file:
                file.write(output)

            parsed_output = json.loads(output)
            print("Successfully generated response.")
            return parsed_output, sessions

        except errors.APIError as aerr:
            print(f"\n** Caught issue from Gemini response: {aerr}")
            return None, None

        except Exception as err:
            print(f"\n** Caught runtime error: {err}")
            return None, None
